
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucnajqoapngtearuafkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbmFqcW9hcG5ndGVhcnVhZmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNDE5NDMsImV4cCI6MjA2MjkxNzk0M30.RItktoPxnmNDb7icRk_G7HthZtZ6XgbgNS9SIuEAfuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
